### ISSUE TITLE
Vertical move button layout on mobile...?

### ISSUE THREAD

**Issue by RasheedAZ** [otacke/h5p-sort-paragraphs#30]
Hi Oliver. Thanks for your amazing work on H5P, especially this module. 

The official example given here actually uses very short sentences, not paragraphs - which typically consist of several sentences. 

https://h5p.org/content-types/sort-the-paragraphs

I was trying it with normal size paragraphs and on mobile, I noticed that the paragraphs resizing to almost double the number of lines because the move buttons on the right were taking a large chunk of the screen (in portrait mode).

So do you think it would be a good idea to have the buttons in a vertical layout instead of beside each other. That way, they will take half of the horizontal space that they're taking now...

![Screen Shot 2022-03-19 at 15 26 48](https://user-images.githubusercontent.com/16827461/159103276-366b2fee-61dd-441b-80a7-eddb0007aa00.png)

**Comment by otacke** [comment]
Hi @RasheedAZ
This content type has been through Joubel's UX testing and did not suggest to have the buttons aligned vertically, but if I find some free time, I'll gladly add that feature.

**Comment by RasheedAZ** [comment]
> This content type has been through Joubel's UX testing and did not suggest to have the buttons aligned vertically, but if I find some free time, I'll gladly add that feature.

Thanks.

**Comment by otacke** [comment]
@RasheedAZ Changed in https://github.com/otacke/h5p-sort-paragraphs/commit/3915b0e65aae962807bb7107cd286ce5e4a66e99. The buttons will now align vertically if all paragraphs offer enough space for both buttons vertically. Please note though that the H5P core team will require to release the update of _Sort the Paragraphs_ unless you build and upload the revised library yourself.
